dependencies:
- name: traefik
  version: "1.77.1"
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: traefik.enabled
- name: aws-alb-ingress-controller
  version: "0.1.10"
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: aws-alb-ingress-controller.enabled
- name: elasticsearch
  version: "1.15.1"
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: elasticsearch.enabled
- name: fluentd-elasticsearch
  version: "1.5.0"
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: fluentd-elasticsearch.enabled
- name: kibana
  version: "1.1.0"
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: kibana.enabled
- name: metrics-server
  version: "2.8.4"
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: metrics-server.enabled
- name: ingress-azure
  version: "1.0.0"
  repository: https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/
  condition: ingress-azure.enabled